pip install pywin32-ctypes==0.2.0
pip install pystyle==2.9
pip install colorama==0.3.9
pip install httpx==0.23.3
pip install pycryptodome==3.17
pip install tls-client==0.1.8
pip install requests
pip install discord
pip install cryptography==40.0.2